site_name: AHK Voicemeeter
site_url: https://jakobshoemaker.github.io/ahk-voicemeeter
site_author: Jake Shoemaker

repo_name: JakobShoemaker/ahk-voicemeeter
repo_url: https://github.com/JakobShoemaker/ahk-voicemeeter

nav:
  - "Getting Started": index.md
  - "API Reference":
    - Voicemeeter:
      - "api-reference/voicemeeter/index.md"
      - DeviceType: "api-reference/voicemeeter/device-type.md"
      - Enum: "api-reference/voicemeeter/enum.md"
      - RemoteError: "api-reference/voicemeeter/remote-error.md"
      - Type: "api-reference/voicemeeter/type.md"

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - tables
  - toc:
      toc_depth: 3

plugins:
  - minify:
      minify_html: true
  - search
  - tags
