on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
      - if: ${{ steps.release.outputs.release_created }}
        run: |
          zip $RELEASE_ASSET LICENSE Voicemeeter.ahk
          gh release upload ${{ steps.release.outputs.tag_name }} $RELEASE_ASSET
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_ASSET: Voicemeeter${{ steps.release.outputs.tag_name }}
